name: devbuddy
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_localizations:
    sdk: flutter

  mongo_dart: ^0.10.3

  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  flutter_native_splash: ^2.4.4
#  sqflite: ^2.4.1

  flutter_dotenv: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#3c4854"
  color_dark: "#3c4854"
  image: assets/images/db.png
  image_dark: assets/images/db.png

android_15:
  image_background_color: "#3c4854"
  image_background_color_dark: "#3c4854"
  image: assets/images/db.png
  image_dark: assets/images/db.png

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/.env
